import BackgroundImage from "../../../assets/newbg2.svg";

// Color palettes only
const colorPalette = {
  light: {
    background: '#efeff1',
    surface: '#ffffff',
    surfaceAlt: '#fbfbfb',
    border: '#dddfe2',
    primary: '#0066ff',
    primaryLight: '#3385ff',
    primaryDark: '#0052cc',
    text: '#232629',
    textSecondary: '#5e646e',
  },
  dark: {
    background: '#1e2a32',
    surface: '#2d3b45',
    surfaceAlt: '#3d4c57',
    border: '#3d4c57',
    primary: '#e0edf3',
    primaryLight: '#e0edf3',
    primaryDark: '#a5b2b8',
    text: '#fbfbfb',
    textSecondary: '#d6d8dc',
  }
};

// Static helpers for style composition
const getBaseStyles = (colors: typeof colorPalette.light | typeof colorPalette.dark) => ({
  mainContainer: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    justifyContent: "stretch",
    width: "100vw",
    height: "100vh",
    backgroundColor: colors.background,
    backgroundImage: `url(${BackgroundImage})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  },
  userInfoBar: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    justifyContent: "center",
    width: '12vw',
    height: '7vh',
    padding: "0.75rem",
    gap: "1rem",
    position: "absolute" as const,
    top: "1rem",
    right: "1rem",
    backgroundColor: colors.surface,
    border: `2px solid ${colors.border}`,
    borderRadius: '20px',
  },
  userAvatar: {
    width: "2.5vw",
    height: "2.5vw",
    borderRadius: "50%",
  },
  icon: {
    fontSize: '1.5rem',
    color: colors.textSecondary,
  },
  sidebar: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    width: '15%',
    height: '100%',
    position: "relative" as const,
    overflowY: "auto" as const,
    fontFamily: "Poppins, sans-serif",
    backgroundColor: '#fff',
    borderTop: `2px solid ${colors.border}`,
    borderRight: `2px solid ${colors.border}`,
    borderBottom: `2px solid ${colors.border}`,
    borderTopRightRadius: "20px",
    borderBottomRightRadius: "20px",
  },
  logoContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "left",
    width: '100%',
    padding: "1rem",
    fontSize: "22px",
    fontWeight: "bold",
    fontFamily: "Poppins, sans-serif",
    backgroundColor: '#fff',
    color: colors.text,
  },
  menu: {
    width: '92%',
    height: "90%",
    marginTop: "1.25rem",
    fontFamily: "Poppins, sans-serif",
    fontSize: "16",
    fontWeight: "500",
    backgroundColor: 'transparent',
    color: colors.textSecondary,
    borderBottomRightRadius: "20px",
    borderRight: 'none',
  },
  logoutButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.6rem",
    width: '90%',
    height: 56,
    position: "absolute" as const,
    bottom: "2vh",
    backgroundColor: '#fff',
    color: '#ff0000',
    fontWeight: 600,
    fontFamily: "Poppins, sans-serif",
    borderRadius: "20px",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
  },
  periodContainer: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    width: "80%",
    height: "80%",
    gap: "1rem",
    position: "relative" as const,
  },
  studentListPanel: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "1rem",
    width: "25%",
    height: "100%",
    padding: "1rem",
    backgroundColor: colors.surface,
    border: `2px solid ${colors.border}`,
    borderRadius: 20,
  },
  rightPanelsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    width: "50%",
    height: "100%",
    gap: "1rem",
  },
  halfHeightPanel: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "1rem",
    width: "100%",
    height: "50%",
    padding: "1rem",
    backgroundColor: colors.surface,
    border: `2px solid ${colors.border}`,
    borderRadius: 20,
  },
  panelTitle: {
    color: colors.primary,
    fontFamily: "Poppins, sans-serif",
    fontSize: "1.5rem",
    marginBottom: "1rem",
    position: "relative" as const,
  },
  studentButton: {
    color: colors.text,
    fontFamily: "Montserrat, sans-serif",
    fontSize: "1rem",
    width: "80%",
    height: "3vw",
    border: `2px solid ${colors.border}`,
    justifyContent: "space-evenly",
  }
});

// Helper for menu config
const getMenuConfig = (colors: typeof colorPalette.light | typeof colorPalette.dark) => ({
  theme: {
    components: {
      Menu: {
        itemSelectedBg: colors.primary,
        itemSelectedColor: '#fbfbfb',
        colorText: colors.textSecondary,
        itemHoverColor: '#fbfbfb',
        itemHoverBg: colors.primary,
        colorBgElevated: colors.surface,
        darkSubMenuItemBg: '#36434d',
        darkItemHoverBg: colors.surfaceAlt,
        darkItemSelectedBg: colors.surfaceAlt,
        darkItemSelectedColor: colors.text,
        darkItemHoverColor: colors.text,
        fontSize: 15,
        padding: 24,
        itemBorderRadius: 20,
        itemHeight: 56,
      },
      Button: {
        defaultHoverBg: colors.surface,
        defaultHoverColor: colors.text,
        defaultBg: colors.surfaceAlt,
        defaultColor: colors.text,
      },
    },
  },
});

export { colorPalette, getBaseStyles, getMenuConfig };